spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://192.168.75.188:2181
  consumer:
    check: false
  protocol:
    port: -1

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml