spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.75.188:2181
  protocol:
    port: -1
    name: dubbo

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
